spring.application.name=FixIt

# Server
server.port=8080

# Database (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/fixit_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# show SQL and parameters (dev only)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT Secret (change in prod)
jwt.secret=aXbYcZ-dEfGhIjKlMnOpQrStUvWxYz12
jwt.expiration=86400000

# Google Maps API Configuration
google.maps.api.key=AIzaSyArvbxR4Hz7jNswrFYrp-kn7ZBx91424FQ

# File Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Twilio SMS Configuration (Demo Mode)
twilio.account.sid=AC7e4f29d328618b70098ad836e942dfeb
twilio.auth.token=7941a63b5a5c1ba81d2775f924be4a31
twilio.phone.number=?+16812085524?

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=udayangayasindu84@gmail.com
spring.mail.password=tzbp rmzw whru ctdb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000


